name: instagram
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7

  # 패키지 목록
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  photo_manager: ^3.7.1
  permission_handler: ^12.0.1
  photo_manager_image_provider: ^2.2.0
  photofilters: ^3.0.1
  image: ^3.3.0
  video_player: ^2.8.6
  chewie: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ⭐️ Asset 경로 설정 (들여쓰기 2칸 주의)
  assets:
    # 1. 공통 이미지 및 비디오
    - assets/images/
    - assets/images/avatar_promo.png
    - assets/images/ic_instagram_logo.png
    - assets/video/
    - assets/icons/

    # 2. 프로필 이미지 폴더
    - assets/images/profiles/

    # 3. 게시물 이미지 폴더들 (오타 없이 정확해야 함)
    - assets/images/posts/kid_go/
    - assets/images/posts/ran/
    - assets/images/posts/areum/
    - assets/images/posts/conan/
    - assets/images/posts/famous/
    - assets/images/posts/inseong/
    - assets/images/posts/mungchi/
    - assets/images/posts/my_posts/
    - assets/images/posts/pupple/
    - assets/images/posts/rose/
    - assets/images/posts/shinichi/
    - assets/images/posts/sin_police/
    - assets/images/posts/triangle/
  